### ISSUE TITLE
Multi function definitions not working

### ISSUE THREAD

**Issue by TcePrepK** [rmordechay/glsl-plugin-idea#37]
![image](https://github.com/user-attachments/assets/760fde6d-5e66-4398-a5f8-e9eb48fff868)
Well as you can see from this image alone, 2 same named functions but different parameters. It is not recognized in the second call. As an addition to this, if you were to "#include" this from some other file, it doesn't even work... (it is very easy to reproduce)
![image](https://github.com/user-attachments/assets/35cd5c51-877e-455d-85b9-561be7fac0cf)

**Comment by walt-grace** [comment]
Hi @TcePrepK 
can you pls send me that as text?

**Comment by TcePrepK** [comment]
```glsl
float smoothFunc(float s) {
    return 3.0 * s * s - 2.0 * s * s * s;
}

float smoothFunc(float a, float b, float x) {
    float lambda = min(1.0, max(0.0, (x - a) / (b - a)));
    return smoothFunc(lambda);
}
```

here is the code, sorry for late response I wasn't so available!
And for the secondary part, calling it with anything reproduces it.
```glsl
smoothFunc(0.0, 1.0, 0.0);
```

**Comment by walt-grace** [comment]
The reason is overloading. The plugin basically stops once it finds the reference and in your case it refers to the first smoothFunc it finds, which, correctly, doesn't recognize the args. I actually didn't even know that overloading is possible in GLSL. Shouldn't be a problem to fix.

**Comment by walt-grace** [comment]
Yeah as you mentioned above it's the overloading. I didn't even know it's possible. I will fix it.
