### ISSUE TITLE
path based importing

### ISSUE THREAD

**Issue by TcePrepK** [rmordechay/glsl-plugin-idea#39]
in the previous version of the `#include`, we would have to write the actual path from the file, like `#include "../utils/mathUtils.glsl"` which was perfect in my case because I am working with multiple files in multiple folders/pathes. With the new version of the `#include`, just writing the name is enough which is ok in my case but I sometimes have multiple files named same things. And my pre handler for the `#include` (basically connecting the included files together in the code) uses these paths as like I have said, I am working with multiple folders. Would it be possible to bring this feature back ? As an option perhaps (if it was already an option, sorry) ? I understand how this current version might be helpful for lot but in my case for example I had to add a special toggling method for the pre handler to stop some `#include`'s from working just so I can get typings from them (for example `"mathUtils.glsl"` doesn't exists, `"utils/mathUtils.glsl"` does)

**Comment by rmordechay** [comment]
Sorry I became pretty busy recently and had to leave the plugin. I will try to get into that the following days.

**Comment by TcePrepK** [comment]
It is all ok, I am closely following the commits (even though I can not understand what the changes are for) and notice you've been gone. I hope everything is ok!

**Comment by rmordechay** [comment]
It's released. Will probably be there tomorrow.

**Comment by rmordechay** [comment]
@TcePrepK Is everything working as expected? Can I close the ticket?

**Comment by TcePrepK** [comment]
Based importing seems to be working, I wasn't able to test more I am pretty busy this month sorry! You can close for now though, tested a few cases and it seems to be working pretty fine!
