### ISSUE TITLE
Incompatible: requires IDE build 242.* or earlier

### ISSUE THREAD

**Issue by ammein** [rmordechay/glsl-plugin-idea#44]
Recently Pycharm has updated new released version that affects the entire plugin ecosystem. Can you update the plugin version so I can continue using your plugin with love? Your plugin helps the entire GLSL developer out here. We wish your plugin will forever be maintained 🥳

**Comment by rmordechay** [comment]
Hi @ammein 
Sorry I didn't have time I will do it today it should be there by tomorrow.

**Comment by ammein** [comment]
It works fine now! Thank you!

**Comment by ammein** [comment]
It works fine now! Thank you!
